<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>FreEMI Terms</title>
<link
	href="<c:url value="${contextcdn}/resources/css/terms-conditions.component.css"/>"
	rel="stylesheet">
<link href="<c:url value="${contextcdn}/resources/css/styles.css"/>"
	rel="stylesheet">
<link href="<c:url value="${contextcdn}/resources/css/homePage.css"/>"
	rel="stylesheet">
<link href="<c:url value="${contextcdn}/resources/css/animate.css"/>"
	type="text/css" rel="stylesheet">
<jsp:include page="include/bootstrap.jsp"></jsp:include>
<script src="<c:url value="${contextcdn}/resources/js/common.js" />"></script>
</head>
<body class="back_set"
	>
	<div class='thetop'></div>
	<jsp:include page="include/header.jsp"></jsp:include>
	<div class="container freemi_container">
		<div class="terms_header">
			<h1 class="terms_header_style">Terms of Use</h1>
		</div>
		<div class="terms_topic">
			<h5>Terms of Use</h5>
		</div>

		<div class="terms_contents_general">

			<p>
				This Agreement sets forth the terms and conditions that apply to the
				access and use of the website&nbsp;<a title="www.freemi.in"
					href="https://www.freemi.in"><span
					style="text-decoration: underline;">www.freemi.in</span></a> and its
				Mobile Application (collectively be referred to as "Website"), which
				is owned and operated by Ntactus Financial Services Private Limited
				and its wholly owned subsidiary FundsOnline Tech Process,
				(hereinafter collectively be referred to as "Company"), which
				companies are incorporated under the laws of India and registered
				under the Companies Act, 1956.
			</p>
			<p>This document/agreement is an electronic record in terms of
				Information Technology Act, 2000 and generated by a computer system
				and does not require any physical or digital signatures. This
				document is published in accordance with the provisions of Rule 3 of
				the Information Technology (Intermediaries guidelines) 2011, that
				provides for the due diligence to be exercised for the access or
				usage of this Website.</p>
			<p>By accessing this Website or registering your information on
				the Website, the users (hereinafter referred to as "you", or "your")
				agree to be bound by the terms and conditions of these Terms of Use
				(TOU), the Legal Disclaimer and the Privacy Policy, as posted
				elsewhere on the Website. You will be subject to the rules,
				guidelines, policies, terms, and conditions applicable to any
				Service that is provided by this Website, and they shall be deemed
				to be incorporated into this TOU and shall be considered as part and
				parcel of this TOU.</p>
			<p>Be sure to return to this page periodically to review the most
				current version of the TOU. We reserve the right at any time, at our
				sole discretion, to change or otherwise modify the TOU without prior
				notice, and your continued access or use of this Website signifies
				your acceptance of the updated or modified TOU.</p>
			<p>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. YOUR
				ACCEPTANCE OF TERMS CONTAINED HEREIN CONSTITUTES THE AGREEMENT
				BETWEEN YOU AND COMPANY FOR THE PURPOSE AS DEFINDED HEREUNDER.</p>

			<h5>1. Description and Acceptance of Services</h5>
			<p>Company, hereby offers you with access to information
				primarily about certain financial products/services including, but
				not restricted, to loan facility, credit cards facility, investment
				services such as Savings account, Fixed Deposits and mutual funds
				(the "Services"). The Website provides loan, credit card facility,
				Savings account, Fixed deposits which is powered by FundsOnline Tech
				Process, whereas investment services relating to mutual funds is
				powered by Ntactus Financial Services Private Limited. In addition,
				Company may provide third party services including but not limited
				to credit check services, UIDAI`s Adhaar based authentication
				service, and any other services to retrieve and use your information
				through third party sites (eg. Bank sites etc.) in conjunction with
				your selection of the Services ("ancillary services"). The above
				said Services and ancillary services are provided on a commercially
				reasonably effort basis and you agree that your participation for
				availing the above mentioned services is purely at your will and
				consent. Your continued usage of the Services and ancillary services
				from time to time would also constitute acceptance of the Terms
				including any updation or modification thereof and you would be
				bound by this Agreement until this Agreement is terminated as per
				provisions defined herein. You agree and authorize Company to share
				your information with its group companies and other third parties,
				in so far as required for joint marketing purposes/offering various
				services/report generations and/or to similar services to provide
				you with various value added services, in association with the
				Services selected by you or otherwise. You agree to receive
				communications through emails, telephone and/or sms, from the
				Company or its third party vendors/business partners regarding the
				Services/ancillary services updates, information/promotional emails
				and/or product announcements. In this context, you agree and consent
				to receive all communications at the mobile number provided, even if
				this mobile number is registered under DND/NCPR list under TRAI
				regulations. And for that purpose, you further authorize Company to
				share/disclose the information to any third party service provider
				or any affiliates, group companies, their authorized agents or third
				party service providers. Company will retain and use your
				information as necessary to comply with our legal obligations,
				resolve disputes and enforce our agreements entered into for
				providing Services and ancillary services.</p>
			<p>&nbsp;</p>
			<h5>2. License and Website Access</h5>
			<p>You acknowledge and agree that Company owns all legal right,
				title and interest in and to the Services, including any
				intellectual property rights which subsist in the Services (whether
				those rights are registered or not). You further acknowledge that
				the Services may contain information which is designated
				confidential by Company and that you shall not disclose such
				information without Company`s prior written consent. The contents of
				the Website, including its "look and feel" (e.g. text, graphics,
				images, logos and button icons), photographs, editorial content,
				notices, software and other material are the owned/licensed by/to
				Company and/or its third Party Service Providers/their licensors and
				are duly protected by them under applicable copyright, trademark and
				other laws. Company grants you a limited license to access and make
				use of the Website, the Services and ancillary services. This
				license does not include any downloading or copying of any kind of
				information for the benefit of another individual, vendor or any
				other third party or to create a derivative work from, modify,
				reverse engineer, reverse assemble or otherwise attempt to discover
				any source code, sell, assign, sublicense, grant a security interest
				in or otherwise transfer any right in the Services. Any unauthorized
				use by you shall terminate the permission or license granted to you.
				By using the Website you agree not to: (i) use this Website or its
				contents for any commercial purpose; (ii) make any speculative,
				false, or fraudulent transaction or any transaction in anticipation
				of demand; (iii) access, monitor or copy any content or information
				of this Website using any robot, spider, scraper, or other automated
				means or any manual process for any purpose without our express
				written permission; (iv) violate the restrictions in any robot
				exclusion headers on this Website or bypass or restrict or
				circumvent other measures employed to prevent or limit access to
				this Website; (v) take any action that imposes, or may impose, in
				our discretion, an unreasonable or disproportionately large load on
				our infrastructure; (vi) deep-link to any portion of this Website
				(including, without limitation, the purchase path for any service)
				for any purpose without our express written permission; or (vii)
				"frame", "mirror" or otherwise incorporate any part of this Website
				into any other website without our prior written authorization.</p>
			<h5>3. Privacy Policy</h5>
			<p>By using the Website, you hereby consent to the use of your
				information as we have outlined in our Privacy Policy. This Privacy
				Policy explains how Company treats your personal information when
				you access the Website and use other ancillary Services.</p>
			<p>&nbsp;</p>
			<h5>4. Your Registration/Account</h5>
			<p>In consideration of your use of the Website and registering
				with us, you represent that you are of legal age to form a binding
				contract and are not a person barred from receiving services under
				the laws of India or other applicable jurisdiction and will only use
				the Website to make legitimate purchases for you or for another
				person for whom you are legally authorized to act (and will inform
				such other persons about the TOU and/or Privacy Policy) that apply
				to the purchase you have made on their behalf (including all rules
				and restrictions applicable thereto). You agree and understand that
				you are solely responsible for maintaining the confidentiality of
				your password which, together with your Login ID (as may be
				applicable in accordance with the Service selected), allows you to
				access the Service. That Login ID and password, together with any
				mobile number or other contact information you provide, form your
				"Registration Information". You agree that you are responsible for
				maintaining the confidentiality of your Login ID and password, and
				for restricting access to your computer. You agree to accept
				responsibility for all activities that occur under your account or
				password. Because of this, we strongly recommend that you exit from
				your account at the end of each session. You agree to notify Company
				immediately of any unauthorized use of your account or any other
				breach of security. You further agree that Company shall not be
				liable for any unauthorized use or access, unless it is proved that
				the unauthorized use or access occurred solely due to reasons
				directly attributable to Company. You shall provide true, accurate,
				current and complete information about yourself and undertake to
				inform/update of any change in your Registration Information
				promptly and keep it up-to-date and accurate at all times, as it has
				a direct bearing on the provision of Services and ancillary services
				by or through Company. You agree not to misrepresent your identity
				nor will you make an attempt to make an unlawful access to the
				Website or use of the Services. Additional terms and conditions will
				apply to your purchase of services that you select. Please read
				these additional terms and conditions carefully.</p>
			<p>&nbsp;</p>
			<h5>5. Eligibility</h5>
			<p>You declare and confirm that you are a resident of India,
				above 18 (Eighteen) years of age, and have the capacity to contract
				as specified under the Indian Contract Act, 1872, while availing the
				Services offered herein via this.</p>
			<p>&nbsp;</p>
			<h5>6. Submitted Content</h5>
			<p>By sharing or submitting any content including any data and
				information on the Website, you agree that you shall be solely
				responsible for all content you post on the Website and Company
				shall not be responsible for any content you make available on or
				through the Website. At Company`s sole discretion, such content may
				be included in the Service and ancillary services (in whole or in
				part or in a modified form). With respect to such content you submit
				or make available on the Website, you grant Company a perpetual,
				irrevocable, non-terminable, worldwide, royalty-free and
				non-exclusive license to use, copy, distribute, publicly display,
				modify, create derivative works, and sublicense such materials or
				any part of such content. You agree that you are fully responsible
				for the content you submit. You are prohibited from posting or
				transmitting to or from this Website: (i) any unlawful, threatening,
				libelous, defamatory, obscene, pornographic, or other material or
				content that would violate rights of publicity and/or privacy or
				that would violate any law; (ii) any commercial material or content
				(including, but not limited to, solicitation of funds, advertising,
				or marketing of any good or services); and (iii) any material or
				content that infringes, misappropriates or violates any copyright,
				trademark, patent right or other proprietary right of any third
				party. You shall be solely liable for any damages resulting from any
				violation of the foregoing restrictions, or any other harm resulting
				from your posting of content to this Website.</p>
			<h5>
				7. Third Party Links/Offers
			</h5>
			<p>This Website or third parties may provide links to other
				websites or resources. Because Company has no control over such
				sites and resources, you acknowledge and agree that Company is not
				responsible for the availability of such external sites or
				resources, and does not endorse and is not responsible or liable for
				any content, advertising, products or other materials on or
				available from such sites or resources. You further acknowledge and
				agree that Company shall not be responsible or liable, directly or
				indirectly, for any damage or loss caused or alleged to be caused by
				or in connection with use of or reliance on any such content, goods
				or services available on or through any such site or resource. Your
				interaction with any third party accessed through the Website is at
				your own risk, and Company will have no liability with respect to
				the acts, omissions, errors, representations, warranties, breaches
				or negligence of any such third parties or for any personal
				injuries, death, property damage, or other damages or expenses
				resulting from your interactions with the third parties.</p>
			<p>&nbsp;</p>
			<h5>
				8. Disclaimer of Warranty
			</h5>
			<p>You expressly understand and agree that your use of the
				Services, ancillary services and all information, products, other
				services and other content (including that of the third parties)
				included in or accessible from the Website is at your sole risk. The
				Services and ancillary services are provided on an "as is" and "as
				available" basis. Company makes no representations, warranties or
				guarantees, express or implied, regarding the accuracy, reliability
				or completeness of the content on the Website or of the services
				(whether or not sponsored by third party service providers), and
				expressly disclaims any warranties of non-infringement or fitness
				for a particular purpose.</p>
			<p>Company and its service providers expressly disclaim all
				warranties of any kind as to the Services, ancillary services and
				all information, products, services and other content (including
				that of the third parties) included in or accessible from the
				services, whether express or implied, including but not limited to
				the implied warranties of merchantability, fitness for a particular
				purpose and non-infringement.</p>
			<p>Company and its service providers make no warranty that (i)
				the services will meet your requirements, (ii) the services will be
				uninterrupted, timely, secure, or error-free, (iii) the results that
				may be obtained from the use of the services will be accurate or
				reliable, (iv) the quality of any products, services, information,
				or other material purchased or obtained by you through the services
				will meet your expectations, and (v) any errors in the technology
				will be corrected.</p>
			<p>&nbsp;</p>
			<h5>
				9. Limitation of Liability
			</h5>
			<p>You expressly understand and agree that Company (including its
				subsidiaries, affiliates, directors, officers, employees,
				representatives and providers) shall not be liable for any direct,
				indirect, incidental, special, consequential or exemplary damages,
				including but not limited to damages for loss of profits,
				opportunity, goodwill, use, data or other intangible losses, even if
				Company has been advised of the possibility of such damages,
				resulting from (i) any failure or delay (including without
				limitation the use of or inability to use any component of the
				Website), or (ii) any use of the Website or content, or (iii) the
				performance or non-performance by us or any provider, even if we
				have been advised of the possibility of damages to such parties or
				any other party, or (b) any damages to or viruses that may infect
				your computer equipment or other property as the result of your
				access to the Website or your downloading of any content from the
				Website.</p>
			<p>&nbsp;</p>
			<p>If, despite the limitation above, Company is found liable for
				any proven and actual loss or damage which arises out of or in any
				way connected with any of the occurrences described above, then you
				agree that the liability of Company shall be restricted to, in the
				aggregate, any Service/transactional fees paid by you to the Company
				in connection with such transaction(s) on this Website, if
				applicable.</p>
			<p>The Website may provide links to other third party websites.
				However, since Company has no control over such third party
				websites, you acknowledge and agree that under no circumstances
				shall Company be liable for your using the services offered or
				provided by any third party service provider.</p>
			<p>&nbsp;</p>
			<h5>
				10.Indemnity
			</h5>
			<p>You agree to indemnify and hold Company (and its affiliates,
				officers, directors, agents and employees) harmless from any and
				against any claims, causes of action, demands, recoveries, losses,
				damages, fines, penalties or other costs or expenses of any kind or
				nature, including reasonable attorneys' fees, or arising out of or
				related to your breach of this TOU, your violation of any law or the
				rights of a third party, or your use of the Website.</p>
			<p>&nbsp;</p>
			<h5>
				11. Additional Terms and Conditions
			</h5>
			<p>Company reserves the right to make changes to the Website,
				related policies and agreements, this TOU and the Privacy Policy at
				any time as it deems fit and proper, including but not limited to
				comply with changes in law or regulation, correct inaccuracies,
				omissions, errors or ambiguities, reflect changes in the process
				flow, scope and nature of the Services and ancillary services,
				company re-organization, market practice or customer requirements.
				Upon any change, Company will notify the updated Terms on the
				Website or other means. Your continued use of the Services and
				ancillary services constitutes acceptance of the changes and an
				agreement to be bound by Terms, as amended. If you do not agree to
				the changes, you may please discontinue your use of the Services and
				ancillary Services.</p>
			<p>&nbsp;</p>
			<p>Company reserves the right to discontinue or suspend,
				temporarily or permanently, the Services/ancillary services, by
				giving reasonable time period notice, on a best effort basis, unless
				it is merely to change certain features/contents of the Services
				and/or Website or maintain the security and integrity of the
				Services. You agree that Company will not be liable to you in any
				manner whatsoever for any modification or discontinuance of the
				Services.</p>
			<p>&nbsp;</p>
			<p>You agree not to use the Services and ancillary services for
				illegal purposes or for the transmission of material that is
				unlawful, harassing, libelous (untrue and damaging to others),
				invasive of another's privacy, abusive, threatening, or obscene, or
				that infringes the rights of other.</p>
			<p>&nbsp;</p>
			<p>Company may, from time to time, announce certain offers with
				intent to promote its Website and/or Services/ ancillary services
				(Promotional Offers). The Promotional Offer(s) would always be
				governed by these TOU plus certain additional terms and conditions,
				if any prescribed. The said additional terms and conditions, if
				prescribed, would be specific to the corresponding Promotional Offer
				only and shall prevail over these TOU, to the extent they may be in
				conflict with these Terms. Company reserves the right to withdraw,
				discontinue, modify, extend and suspend the Promotional Offer(s) and
				the terms governing it, at its sole discretion.</p>
			<p>&nbsp;</p>
			<h5>
				12. General
			</h5>
			<p>If any of these conditions are deemed invalid, void, or for
				any reason unenforceable, the parties agree that the court should
				endeavor to give effect to the parties intentions as reflected in
				the provision, and the unenforceable condition shall be deemed
				severable and shall not affect the validity and enforceability of
				any remaining condition. Headings are for reference purposes only
				and do not limit the scope or extent of such section. This TOU and
				the relationship between you and Company will be governed by the
				laws of the India without regard to its conflict of law provisions.
				Any dispute, controversy or claim arising out of or in relation to
				this Agreement, including a breach or termination thereof, shall be
				settled by a sole arbitrator to be appointed mutually by Company and
				you, in accordance with the provisions of the Arbitration and
				Conciliation Act, 1996, or amendment thereto. In the event we are
				unable to reach an agreement on the sole arbitrator, we agree to
				have a panel of three arbitrators appointed, of which one shall be
				appointed by each of us, and the third arbitrator appointed by the
				two arbitrators. The venue for arbitration shall be Gurgaon. The
				arbitral procedure shall be conducted in the English language and
				any award or awards shall be rendered in English. The Website/Mobile
				App specifically prohibits you from usage of any of its Services in
				any countries or jurisdictions that do not corroborate to all
				stipulations of these Terms. The Website is specifically for users
				in the territory of India. In case of any dispute, either judicial
				or quasi-judicial, the same will be subject to the laws of India,
				with the courts in Gurgaon having exclusive jurisdiction. The
				failure of Company to act with respect to a breach by you or others
				does not waive its right to act with respect to subsequent or
				similar breaches. This TOU constitutes the entire agreement between
				you and Company and governs your use of the Website, superseding any
				prior agreements between you and Company with respect to the
				Website.</p>

		</div>

	</div>
	<div class='scrolltop'>
		<div class='scroll icon bounceIn'>
			<i class="fa fa-4x fa-angle-up" style="font-size: 30px;"></i>
		</div>
	</div>
	<jsp:include page="include/footer.jsp"></jsp:include>
</body>
</html>